import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'de' | 'en' | 'nl';
export type LanguageLabel = 'GER' | 'ENG' | 'DUT';

export interface LanguageOption {
  code: LanguageCode;
  label: LanguageLabel;
  flag: string;
}

export const languages: LanguageOption[] = [
  { code: 'en', label: 'ENG', flag: '🇬🇧' },
  { code: 'de', label: 'GER', flag: '🇩🇪' },
  { code: 'nl', label: 'DUT', flag: '🇳🇱' },
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav items
    'nav.dashboard': 'Dashboard',
    'nav.leads': 'Leads',
    'nav.contacts': 'Contacts',
    'nav.companies': 'Companies',
    'nav.deals': 'Deals & Pipeline',
    'nav.tasks': 'Tasks',
    'nav.activities': 'Activities',
    'nav.reports': 'Reports & Analytics',
    'nav.ai': 'Inbox AI Assistant',
    'nav.admin': 'Admin Panel',
    'nav.settings': 'Settings',
    'nav.rbac_role': 'RBAC Role',
    'nav.tier_enterprise': 'Enterprise Tier',

    // TopNav
    'header.search_placeholder': 'Search leads, deals, contacts... (Press ↵)',
    'header.new_record': 'New Record',
    'header.new_lead': 'New Lead',
    'header.new_deal': 'New Opportunity / Deal',
    'header.new_task': 'New Task',
    'header.log_activity': 'Log Activity',
    'header.tenant': 'Tenant',
    'header.switch_tenant': 'Switch Tenant Workspace',
    'header.select_tenant': 'Select Tenant Workspace',
    'header.simulate_role': 'Simulate Role (RBAC)',
    'header.switch_role_title': 'Switch Demo User Role',
    'header.notifications': 'Notifications',
    'header.mark_all_read': 'Mark all as read',
    'header.admin_console': 'Admin Console',
    'header.workspace_settings': 'Workspace Settings',
    'header.sign_out': 'Sign Out / Switch User',
    'header.toggle_theme': 'Toggle color theme',
    'header.language': 'Language',
    'header.notif_lead_title': 'New high-priority lead scored 92/100',
    'header.notif_lead_desc': 'Gaurav Bhasin from OmniRetail visited the pricing calculator.',
    'header.notif_deal_title': 'Deal stage progressed to Negotiation',
    'header.notif_deal_desc': 'ABC Technologies - CRM Implementation moved by Vikramaditya.',
    'header.notif_task_title': 'Task Due Today',
    'header.notif_task_desc': 'Schedule executive architectural demo with Rajesh Kulkarni.',
    'header.time_10m': '10 mins ago',
    'header.time_1h': '1 hour ago',
    'header.time_3h': '3 hours ago',

    // Common Actions & Labels
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.export_csv': 'Export CSV',
    'common.search': 'Search',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.details': 'Details',
    'common.records': 'records',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.all': 'All',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.stage': 'Stage',
    'common.value': 'Value',
    'common.owner': 'Owner',
    'common.assignee': 'Assignee',
    'common.date': 'Date',
    'common.due_date': 'Due Date',
    'common.loading': 'Loading...',
    'common.empty': 'No records found',
    'common.confirm': 'Confirm',
    'common.copied': 'Copied to clipboard',
    'common.copy': 'Copy',
    'common.processing': 'Processing...',
    'common.all_statuses': 'All Statuses',
    'common.all_sources': 'All Sources',
    'common.all_scores': 'All Scores',
    'common.all_stages': 'All Stages',
    'common.all_priorities': 'All Priorities',
    'common.all_types': 'All Types',
    'common.all_verticals': 'All Verticals',
    'common.all_roles': 'All Roles',
    'common.kanban': 'Kanban',
    'common.list': 'List',
    'common.overview': 'Overview',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.company': 'Company',
    'common.account': 'Account',
    'common.role': 'Role',
    'common.title': 'Title',
    'common.description': 'Description',
    'common.type': 'Type',
    'common.source': 'Source',
    'common.notes': 'Notes',
    'common.created': 'Created',
    'common.updated': 'Updated',
    'common.touchpoints': 'touchpoints',
    'common.accounts': 'accounts',
    'common.scheduled': 'scheduled',
    'common.opportunities': 'opportunities',

    // Statuses
    'status.New': 'New',
    'status.Contacted': 'Contacted',
    'status.Qualified': 'Qualified',
    'status.Unqualified': 'Unqualified',
    'status.Converted': 'Converted',
    'status.Proposal': 'Proposal',
    'status.Negotiation': 'Negotiation',
    'status.Won': 'Closed Won',
    'status.Lost': 'Closed Lost',
    'status.Completed': 'Completed',
    'status.Pending': 'Pending',
    'status.In Progress': 'In Progress',
    'status.Overdue': 'Overdue',
    'status.Active': 'Active',
    'status.Inactive': 'Inactive',
    'status.Customer': 'Customer',
    'status.Prospect': 'Prospect',

    // Priorities
    'priority.Low': 'Low',
    'priority.Medium': 'Medium',
    'priority.High': 'High',
    'priority.Urgent': 'Urgent',

    // Roles
    'role.Super Admin': 'Super Admin',
    'role.Admin': 'Admin',
    'role.Manager': 'Manager',
    'role.Sales': 'Sales',
    'role.Viewer': 'Viewer',

    // Stages
    'stage.New': 'Discovery',
    'stage.Qualified': 'Qualified',
    'stage.Proposal': 'Proposal / RFP',
    'stage.Negotiation': 'Negotiation',
    'stage.Won': 'Closed Won',
    'stage.Lost': 'Closed Lost',

    // Activity Types
    'activity.Call': 'Call',
    'activity.Email': 'Email',
    'activity.Meeting': 'Meeting',
    'activity.Demo': 'Demo',
    'activity.Note': 'Note',
    'activity.Follow-up': 'Follow-up',

    // Sources
    'source.Website': 'Website',
    'source.Referral': 'Referral',
    'source.LinkedIn': 'LinkedIn',
    'source.Advertisement': 'Advertisement',
    'source.Cold Call': 'Cold Call',

    // Periods
    'period.Today': 'Today',
    'period.7 Days': '7 Days',
    'period.30 Days': '30 Days',
    'period.90 Days': '90 Days',
    'period.This Year': 'This Year',

    // Pagination
    'pagination.showing': 'Showing',
    'pagination.to': 'to',
    'pagination.of': 'of',
    'pagination.results': 'results',
    'pagination.rows': 'Rows:',
    'pagination.page': 'Page',

    // Modals
    'modal.create_lead_title': 'Create New Lead',
    'modal.create_lead_subtitle': 'Add an inbound prospect to your CRM database with AI scoring.',
    'modal.full_name': 'Full Name',
    'modal.company': 'Company / Organization',
    'modal.email': 'Email',
    'modal.phone': 'Phone',
    'modal.est_value': 'Estimated Value (₹)',
    'modal.acq_source': 'Acquisition Source',
    'modal.save_lead': 'Save Lead',
    'modal.create_deal_title': 'Create New Sales Opportunity',
    'modal.create_deal_subtitle': 'Add a deal directly to the sales pipeline Kanban board.',
    'modal.deal_title': 'Deal Title',
    'modal.account_company': 'Account / Company',
    'modal.deal_value': 'Deal Value (₹)',
    'modal.initial_stage': 'Initial Stage',
    'modal.target_close_date': 'Target Close Date',
    'modal.create_deal': 'Create Deal',
    'modal.schedule_task_title': 'Schedule New Task',
    'modal.schedule_task_subtitle': 'Assign an action item to keep deal momentum high.',
    'modal.task_title': 'Task Title',
    'modal.related_account': 'Related Account / Company',
    'modal.due_date': 'Due Date',
    'modal.save_task': 'Save Task',
    'modal.log_activity_title': 'Log Customer Activity',
    'modal.log_activity_subtitle': 'Record touchpoints across email, phone, or meetings.',
    'modal.activity_type': 'Activity Type',
    'modal.subject': 'Subject / Title',
    'modal.discussion_notes': 'Discussion Notes',
    'modal.record_activity': 'Record Activity',
    'modal.convert_lead_title': 'Convert Lead to Contact & Opportunity',
    'modal.convert_lead_desc': 'Convert this scored lead into an active sales opportunity and company directory record.',
    'modal.convert_create_deal': 'Create active opportunity in pipeline',
    'modal.confirm_convert': 'Convert Lead',

    // Dashboard
    'dashboard.title': 'Executive CRM Dashboard',
    'dashboard.subtitle': 'Real-time pipeline performance, conversion telemetry, and team activity.',
    'dashboard.live_badge': 'Live Real-Time',
    'dashboard.total_leads': 'Total Leads',
    'dashboard.new_inbound': 'New Inbound',
    'dashboard.open_deals': 'Open Deals',
    'dashboard.pipeline_value': 'Pipeline Value',
    'dashboard.won_revenue': 'Won Revenue',
    'dashboard.conversion_rate': 'Win Rate',
    'dashboard.revenue_chart_title': 'Revenue Bookings vs Quota Target (₹ Lakhs)',
    'dashboard.revenue_chart_subtitle': 'Monthly revenue closed against organizational quotas',
    'dashboard.closed_won_legend': 'Closed Won (₹L)',
    'dashboard.quota_target_legend': 'Quota Target (₹L)',
    'dashboard.pipeline_overview': 'Pipeline Stages Breakdown',
    'dashboard.active_forecast': 'Active Weighted Win Forecast',
    'dashboard.upcoming_tasks': 'Upcoming Action Tasks',
    'dashboard.high_intent_leads': 'High-Intent AI Leads',
    'dashboard.recent_activities': 'Recent Touchpoints',
    'dashboard.view_pipeline': 'View Pipeline Board',
    'dashboard.view_tasks': 'View Board',
    'dashboard.view_leads': 'All Leads',
    'dashboard.view_activities': 'Audit Log',
    'dashboard.recent_touchpoints': 'Recent Touchpoints',

    // Leads Page
    'leads.title': 'Leads Management',
    'leads.subtitle': 'Capture, score, qualify, and convert prospective accounts.',
    'leads.new_lead_btn': 'Add Lead',
    'leads.search_placeholder': 'Search leads by name, company, email...',
    'leads.score': 'AI Score',
    'leads.convert': 'Convert',
    'leads.inspect': 'Inspect Profile',
    'leads.export': 'Export CSV',
    'leads.filter_hot': 'AI Score > 80 (Hot)',
    'leads.filter_warm': 'AI Score > 60 (Warm)',
    'leads.bulk_selected': 'leads selected',
    'leads.bulk_status': 'Bulk Update Status:',
    'leads.col_lead': 'Lead',
    'leads.col_company': 'Company',
    'leads.col_score': 'AI Score',
    'leads.col_value': 'Est. Value',
    'leads.col_source': 'Source',
    'leads.col_status': 'Status',
    'leads.col_owner': 'Owner',
    'leads.col_actions': 'Actions',
    'leads.drawer_title': 'Lead Profile Details',
    'leads.drawer_notes': 'Qualification Notes & Intelligence',
    'leads.delete_confirm_title': 'Delete Lead Record',
    'leads.delete_confirm_msg': 'Are you sure you want to permanently delete this lead? This action cannot be undone.',

    // Contacts Page
    'contacts.title': 'Customer Contacts',
    'contacts.subtitle': 'Stakeholder contacts, account decision makers, and communication channels.',
    'contacts.new_contact': 'Add Contact',
    'contacts.search': 'Search contacts by name, role, email...',
    'contacts.col_name': 'Contact Name',
    'contacts.col_account': 'Account / Company',
    'contacts.col_info': 'Contact Info',
    'contacts.col_owner': 'Owner',
    'contacts.col_last_contact': 'Last Contact',
    'contacts.drawer_title': 'Contact Profile Details',
    'contacts.delete_confirm_title': 'Delete Contact',
    'contacts.delete_confirm_msg': 'Are you sure you want to delete this contact stakeholder?',

    // Companies Page
    'companies.title': 'Enterprise Accounts & Companies',
    'companies.subtitle': 'Directory of client organizations, corporate entities, and tier accounts.',
    'companies.new_company': 'Add Company',
    'companies.search': 'Search companies by name, vertical, city...',
    'companies.col_name': 'Company / Account',
    'companies.col_vertical': 'Industry Vertical',
    'companies.col_rev': 'Annual Revenue',
    'companies.col_size': 'Team Size',
    'companies.col_tier': 'Account Tier',
    'companies.col_location': 'HQ Location',
    'companies.drawer_title': 'Company Account Profile',
    'companies.delete_confirm_title': 'Delete Company Account',
    'companies.delete_confirm_msg': 'Are you sure you want to delete this company account?',

    // Deals Page
    'deals.title': 'Sales Pipeline & Kanban',
    'deals.subtitle': 'Visualize deal velocity, stage progression, and revenue probability.',
    'deals.new_deal': 'Add Deal',
    'deals.total_pipeline': 'Total Pipeline',
    'deals.weighted_forecast': 'Weighted Forecast',
    'deals.avg_deal_size': 'Avg Deal Size',
    'deals.col_title': 'Deal Title',
    'deals.col_account': 'Account',
    'deals.col_stage': 'Stage',
    'deals.col_value': 'Deal Value',
    'deals.col_prob': 'Probability',
    'deals.col_close': 'Target Close Date',
    'deals.delete_confirm_title': 'Delete Pipeline Deal',
    'deals.delete_confirm_msg': 'Are you sure you want to remove this deal from the sales pipeline?',

    // Tasks Page
    'tasks.title': 'Tasks & Follow-Ups',
    'tasks.subtitle': 'Operational action items, milestones, calls, and follow-ups.',
    'tasks.new_task': 'New Task',
    'tasks.pending_tab': 'Pending Tasks',
    'tasks.completed_tab': 'Completed Tasks',
    'tasks.col_task': 'Task Title',
    'tasks.col_related': 'Related Account',
    'tasks.col_due': 'Due Date',
    'tasks.col_priority': 'Priority',
    'tasks.col_status': 'Status',
    'tasks.col_assignee': 'Assignee',
    'tasks.delete_confirm_title': 'Delete Task',
    'tasks.delete_confirm_msg': 'Are you sure you want to delete this task?',

    // Activities Page
    'activities.title': 'Activity Stream & Audit Log',
    'activities.subtitle': 'Complete chronology of calls, emails, product demos, meetings, and internal notes.',
    'activities.log_activity': 'Log Activity',
    'activities.timeline_view': 'Activity Stream',

    // Reports Page
    'reports.title': 'Revenue & Pipeline Intelligence',
    'reports.subtitle': 'Executive revenue analytics, conversion funnels, quota attainment, and lead acquisition attribution.',
    'reports.export_pdf': 'Export CSV',
    'reports.total_pipeline_val': 'Total Pipeline Value',
    'reports.won_revenue_val': 'Closed Won Revenue',
    'reports.avg_deal_cycle': 'Average Deal Cycle',
    'reports.win_conversion_rate': 'Win Conversion Rate',
    'reports.rep_leaderboard': 'Sales Representative Quota Leaderboard',
    'reports.col_rep': 'Representative',
    'reports.col_deals_won': 'Deals Won',
    'reports.col_rev_lakhs': 'Revenue (₹ Lakhs)',
    'reports.col_win_rate': 'Win Rate',
    'reports.col_quota': 'Quota Attainment',
    'reports.funnel_title': 'Lead to Customer Conversion Funnel',
    'reports.stage_breakdown': 'Pipeline Distribution by Stage',

    // AI Assistant
    'ai.title': 'Inbox AI Assistant',
    'ai.subtitle': 'AI-powered intelligence copilot by Inbox Infotech for sales forecasting, lead qualification, and customer follow-ups.',
    'ai.gemini_badge': 'Gemini Ready',
    'ai.clear_chat': 'Clear Chat History',
    'ai.send': 'Send',
    'ai.copilot_name': 'Inbox AI Copilot',
    'ai.suggested_actions': 'Suggested Actions',
    'ai.input_placeholder': 'Ask Inbox AI to forecast revenue, summarize leads, audit deal risks, or draft emails...',
    'ai.prompt_deals_attention': 'Deals Needing Attention',
    'ai.prompt_top_leads': 'Top Priority Leads',
    'ai.prompt_draft_email': 'Draft Follow-Up Email',
    'ai.prompt_closing_soon': 'Deals Closing This Month',

    // Admin Panel
    'admin.title': 'Admin & Governance Console',
    'admin.subtitle': 'Global system health, employee RBAC privileges, tenant policies, and database safeguards.',
    'admin.super_access': 'Super Admin Access',
    'admin.tab_users': 'Employee Access & RBAC',
    'admin.tab_tenant': 'Tenant Workspaces',
    'admin.tab_security': 'Security Audit Log',
    'admin.tab_database': 'Database Safeguards',
    'admin.add_employee': 'Add Employee',
    'admin.backup_db': 'Backup Database (JSON)',
    'admin.factory_reset': 'Factory Reset CRM',
    'admin.col_employee': 'Employee Name',
    'admin.col_email': 'Email Address',
    'admin.col_role': 'Assigned Role',
    'admin.col_dept': 'Department',
    'admin.col_status': 'Account Status',
    'admin.col_actions': 'Actions',
    'admin.col_event': 'Action / Event',
    'admin.col_user': 'User Account',
    'admin.col_target': 'Resource Target',
    'admin.col_ip': 'IP Address',
    'admin.col_timestamp': 'Timestamp',

    // Settings
    'settings.title': 'System Administration & Settings',
    'settings.subtitle': 'Configure tenant workspaces, user authorization roles, scoring heuristics, and integration endpoints.',
    'settings.language_preference': 'Language & Locale',
    'settings.select_language': 'Select Interface Language',
    'settings.tab_org': 'Organization Profile',
    'settings.tab_team': 'Team & Roles (RBAC)',
    'settings.tab_fields': 'Custom Field Definitions',
    'settings.tab_scoring': 'Lead Scoring Rules',
    'settings.tab_api': 'API & Backend Readiness',
    'settings.org_info': 'Workspace Information',
    'settings.company_name': 'Company / Workspace Name',
    'settings.base_currency': 'Default Base Currency',
    'settings.timezone': 'Timezone',
    'settings.fiscal_year': 'Fiscal Year Start Month',
    'settings.save_profile': 'Save Profile',

    // Login
    'login.title': 'Sign in to Inbox CRM',
    'login.admin_portal': 'Administrator Portal',
    'login.employee_workspace': 'Employee Workspace',
    'login.subtitle': 'Sign in to access your Inbox Infotech CRM instance',
    'login.work_email': 'Work Email',
    'login.password': 'Password',
    'login.remember_me': 'Remember this device',
    'login.sign_in_btn': 'Sign In to Workspace',
    'login.quick_demo_roles': 'Quick Demo Roles (1-Click Login)',
    'login.live_instance': 'Live Cloud Instance',
    'login.admin_tab': 'Admin',
    'login.staff_tab': 'Staff',
    'login.email_required': 'Please enter your work email address',
    'login.pass_required': 'Please enter your password',
    'login.success': 'Login successful! Welcome to Inbox CRM.',
    'login.invalid': 'Invalid email or password. Please verify your credentials.',
    'login.admin_login': 'Admin Login',
    'login.staff_login': 'Staff / User Login',
    'login.forgot_password': 'Forgot password?',
    'login.credentials_guide': 'Demo Credentials Guide',
    'login.autofill': 'Auto-Fill',
    'login.credentials_filled': 'Credentials filled in form!',
    'login.auth_failed': 'Authentication Failed',
    'login.tls_encrypted': '256-bit TLS Encrypted',
    'login.preconfigured': 'Pre-configured',
    'login.log_in': 'Log In',
    'login.sign_in_as': 'Sign in as {role}',
    'login.enter_password': 'Enter password',
    'login.rights_reserved': 'All Rights Reserved • Enterprise CRM Solution',
    'login.signed_in_as': 'Signed in successfully as {role}!',

    // Guide Modal
    'guide.title': 'NexusCRM Client Demonstration Guide',
    'guide.subtitle': 'Follow this proven 6-step walkthrough script to present a compelling SaaS demonstration to prospects or investors.',
    'guide.tip': 'Demonstration Tip: All data in this application is live and interactive in local memory. You can create records, drag deals, and log activities safely.',
    'guide.got_it': "Got It, Let's Demo",
  },
  de: {
    // Nav items
    'nav.dashboard': 'Dashboard',
    'nav.leads': 'Leads',
    'nav.contacts': 'Kontakte',
    'nav.companies': 'Unternehmen',
    'nav.deals': 'Deals & Pipeline',
    'nav.tasks': 'Aufgaben',
    'nav.activities': 'Aktivitäten',
    'nav.reports': 'Berichte & Analysen',
    'nav.ai': 'Inbox KI-Assistent',
    'nav.admin': 'Admin-Bereich',
    'nav.settings': 'Einstellungen',
    'nav.rbac_role': 'RBAC-Rolle',
    'nav.tier_enterprise': 'Enterprise-Tarif',

    // TopNav
    'header.search_placeholder': 'Leads, Deals, Kontakte suchen... (Drücken Sie ↵)',
    'header.new_record': 'Neuer Datensatz',
    'header.new_lead': 'Neuer Lead',
    'header.new_deal': 'Neuer Deal / Chance',
    'header.new_task': 'Neue Aufgabe',
    'header.log_activity': 'Aktivität erfassen',
    'header.tenant': 'Mandant',
    'header.switch_tenant': 'Mandanten-Arbeitsbereich wechseln',
    'header.select_tenant': 'Mandanten-Arbeitsbereich wählen',
    'header.simulate_role': 'Rolle simulieren (RBAC)',
    'header.switch_role_title': 'Demo-Benutzerrolle wechseln',
    'header.notifications': 'Benachrichtigungen',
    'header.mark_all_read': 'Alle als gelesen markieren',
    'header.admin_console': 'Admin-Konsole',
    'header.workspace_settings': 'Arbeitsbereich-Einstellungen',
    'header.sign_out': 'Abmelden / Benutzer wechseln',
    'header.toggle_theme': 'Farbdesign wechseln',
    'header.language': 'Sprache',
    'header.notif_lead_title': 'Neuer Lead mit hoher Priorität (Score: 92/100)',
    'header.notif_lead_desc': 'Gaurav Bhasin von OmniRetail hat den Preiskalkulator besucht.',
    'header.notif_deal_title': 'Deal-Phase zu Verhandlung gewechselt',
    'header.notif_deal_desc': 'ABC Technologies - CRM-Implementierung von Vikramaditya verschoben.',
    'header.notif_task_title': 'Aufgabe heute fällig',
    'header.notif_task_desc': 'Architektur-Präsentation mit Rajesh Kulkarni planen.',
    'header.time_10m': 'Vor 10 Min.',
    'header.time_1h': 'Vor 1 Stunde',
    'header.time_3h': 'Vor 3 Stunden',

    // Common Actions & Labels
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.filter': 'Filtern',
    'common.export': 'Exportieren',
    'common.export_csv': 'CSV exportieren',
    'common.search': 'Suchen',
    'common.actions': 'Aktionen',
    'common.view': 'Ansehen',
    'common.details': 'Details',
    'common.records': 'Einträge',
    'common.close': 'Schließen',
    'common.refresh': 'Aktualisieren',
    'common.previous': 'Zurück',
    'common.next': 'Weiter',
    'common.all': 'Alle',
    'common.status': 'Status',
    'common.priority': 'Priorität',
    'common.stage': 'Phase',
    'common.value': 'Wert',
    'common.owner': 'Zuständig',
    'common.assignee': 'Zugewiesen an',
    'common.date': 'Datum',
    'common.due_date': 'Fälligkeitsdatum',
    'common.loading': 'Laden...',
    'common.empty': 'Keine Datensätze gefunden',
    'common.confirm': 'Bestätigen',
    'common.copied': 'In die Zwischenablage kopiert',
    'common.copy': 'Kopieren',
    'common.processing': 'Wird verarbeitet...',
    'common.all_statuses': 'Alle Status',
    'common.all_sources': 'Alle Quellen',
    'common.all_scores': 'Alle Scores',
    'common.all_stages': 'Alle Phasen',
    'common.all_priorities': 'Alle Prioritäten',
    'common.all_types': 'Alle Typen',
    'common.all_verticals': 'Alle Branchen',
    'common.all_roles': 'Alle Rollen',
    'common.kanban': 'Kanban',
    'common.list': 'Liste',
    'common.overview': 'Übersicht',
    'common.name': 'Name',
    'common.email': 'E-Mail',
    'common.phone': 'Telefon',
    'common.company': 'Unternehmen',
    'common.account': 'Kunde / Account',
    'common.role': 'Rolle',
    'common.title': 'Titel',
    'common.description': 'Beschreibung',
    'common.type': 'Typ',
    'common.source': 'Quelle',
    'common.notes': 'Notizen',
    'common.created': 'Erstellt',
    'common.updated': 'Aktualisiert',
    'common.touchpoints': 'Kontaktpunkte',
    'common.accounts': 'Kunden',
    'common.scheduled': 'geplant',
    'common.opportunities': 'Verkaufschancen',

    // Statuses
    'status.New': 'Neu',
    'status.Contacted': 'Kontaktiert',
    'status.Qualified': 'Qualifiziert',
    'status.Unqualified': 'Nicht qualifiziert',
    'status.Converted': 'Konvertiert',
    'status.Proposal': 'Angebot',
    'status.Negotiation': 'Verhandlung',
    'status.Won': 'Gewonnen',
    'status.Lost': 'Verloren',
    'status.Completed': 'Abgeschlossen',
    'status.Pending': 'Ausstehend',
    'status.In Progress': 'In Bearbeitung',
    'status.Overdue': 'Überfällig',
    'status.Active': 'Aktiv',
    'status.Inactive': 'Inaktiv',
    'status.Customer': 'Kunde',
    'status.Prospect': 'Interessent',

    // Priorities
    'priority.Low': 'Niedrig',
    'priority.Medium': 'Mittel',
    'priority.High': 'Hoch',
    'priority.Urgent': 'Dringend',

    // Roles
    'role.Super Admin': 'Super Admin',
    'role.Admin': 'Admin',
    'role.Manager': 'Manager',
    'role.Sales': 'Vertrieb',
    'role.Viewer': 'Betrachter',

    // Stages
    'stage.New': 'Erstkontakt',
    'stage.Qualified': 'Qualifiziert',
    'stage.Proposal': 'Angebot / Ausschreibung',
    'stage.Negotiation': 'Verhandlung',
    'stage.Won': 'Gewonnen',
    'stage.Lost': 'Verloren',

    // Activity Types
    'activity.Call': 'Anruf',
    'activity.Email': 'E-Mail',
    'activity.Meeting': 'Meeting',
    'activity.Demo': 'Produkt-Demo',
    'activity.Note': 'Notiz',
    'activity.Follow-up': 'Nachfassung',

    // Sources
    'source.Website': 'Webseite',
    'source.Referral': 'Empfehlung',
    'source.LinkedIn': 'LinkedIn',
    'source.Advertisement': 'Werbung',
    'source.Cold Call': 'Kaltakquise',

    // Periods
    'period.Today': 'Heute',
    'period.7 Days': '7 Tage',
    'period.30 Days': '30 Tage',
    'period.90 Days': '90 Tage',
    'period.This Year': 'Dieses Jahr',

    // Pagination
    'pagination.showing': 'Zeige',
    'pagination.to': 'bis',
    'pagination.of': 'von',
    'pagination.results': 'Ergebnissen',
    'pagination.rows': 'Zeilen:',
    'pagination.page': 'Seite',

    // Modals
    'modal.create_lead_title': 'Neuen Lead erstellen',
    'modal.create_lead_subtitle': 'Fügen Sie einen Interessenten mit KI-Scoring zu Ihrer CRM-Datenbank hinzu.',
    'modal.full_name': 'Vollständiger Name',
    'modal.company': 'Unternehmen / Organisation',
    'modal.email': 'E-Mail',
    'modal.phone': 'Telefon',
    'modal.est_value': 'Geschätzter Wert (₹)',
    'modal.acq_source': 'Akquisekanal',
    'modal.save_lead': 'Lead speichern',
    'modal.create_deal_title': 'Neue Verkaufschance erstellen',
    'modal.create_deal_subtitle': 'Fügen Sie einen Deal direkt zum Kanban-Board der Vertriebspipeline hinzu.',
    'modal.deal_title': 'Deal-Titel',
    'modal.account_company': 'Kunde / Unternehmen',
    'modal.deal_value': 'Deal-Wert (₹)',
    'modal.initial_stage': 'Ausgangsphase',
    'modal.target_close_date': 'Geplantes Abschlussdatum',
    'modal.create_deal': 'Deal erstellen',
    'modal.schedule_task_title': 'Neue Aufgabe planen',
    'modal.schedule_task_subtitle': 'Weisen Sie eine Folgeaufgabe zu, um den Verkaufsfortschritt zu sichern.',
    'modal.task_title': 'Aufgabentitel',
    'modal.related_account': 'Zugehöriges Unternehmen',
    'modal.due_date': 'Fälligkeitsdatum',
    'modal.save_task': 'Aufgabe speichern',
    'modal.log_activity_title': 'Kundenaktivität protokollieren',
    'modal.log_activity_subtitle': 'Erfassen Sie Kontaktpunkte über E-Mail, Telefon oder Meetings.',
    'modal.activity_type': 'Aktivitätstyp',
    'modal.subject': 'Betreff / Titel',
    'modal.discussion_notes': 'Gesprächsnotizen',
    'modal.record_activity': 'Aktivität speichern',
    'modal.convert_lead_title': 'Lead in Kontakt & Deal umwandeln',
    'modal.convert_lead_desc': 'Konvertieren Sie diesen qualifizierten Lead in eine aktive Verkaufschance und einen Firmenkontakt.',
    'modal.convert_create_deal': 'Aktiven Deal in der Vertriebspipeline anlegen',
    'modal.confirm_convert': 'Lead umwandeln',

    // Dashboard
    'dashboard.title': 'CRM-Vorstands-Dashboard',
    'dashboard.subtitle': 'Echtzeit-Pipeline-Performance, Konversions-Telemetrie und Teamaktivitäten.',
    'dashboard.live_badge': 'Live Echtzeit',
    'dashboard.total_leads': 'Gesamte Leads',
    'dashboard.new_inbound': 'Neue Inbound-Leads',
    'dashboard.open_deals': 'Offene Deals',
    'dashboard.pipeline_value': 'Pipeline-Wert',
    'dashboard.won_revenue': 'Gewonnener Umsatz',
    'dashboard.conversion_rate': 'Abschlussquote',
    'dashboard.revenue_chart_title': 'Umsatzbuchungen vs. Quotaziel (₹ Lakhs)',
    'dashboard.revenue_chart_subtitle': 'Monatlich abgeschlossener Umsatz im Vergleich zu Unternehmenszielen',
    'dashboard.closed_won_legend': 'Gewonnen (₹L)',
    'dashboard.quota_target_legend': 'Zielvorgabe (₹L)',
    'dashboard.pipeline_overview': 'Verteilung der Vertriebsphasen',
    'dashboard.active_forecast': 'Aktive gewichtete Gewinnprognose',
    'dashboard.upcoming_tasks': 'Anstehende Aufgaben',
    'dashboard.high_intent_leads': 'KI-qualifizierte Leads mit hoher Kaufabsicht',
    'dashboard.recent_activities': 'Neueste Aktivitäten',
    'dashboard.view_pipeline': 'Pipeline-Board anzeigen',
    'dashboard.view_tasks': 'Board anzeigen',
    'dashboard.view_leads': 'Alle Leads',
    'dashboard.view_activities': 'Audit-Protokoll',
    'dashboard.recent_touchpoints': 'Neueste Aktivitäten',

    // Leads Page
    'leads.title': 'Leads-Verwaltung',
    'leads.subtitle': 'Interessenten mit automatisiertem KI-Lead-Scoring erfassen und qualifizieren.',
    'leads.new_lead_btn': 'Neuer Lead',
    'leads.search_placeholder': 'Leads nach Name, E-Mail, Firma suchen...',
    'leads.score': 'KI-Score',
    'leads.convert': 'Umwandeln',
    'leads.inspect': 'Profil prüfen',
    'leads.export': 'CSV exportieren',
    'leads.filter_hot': 'KI-Score > 80 (Heiß)',
    'leads.filter_warm': 'KI-Score > 60 (Warm)',
    'leads.bulk_selected': 'Leads ausgewählt',
    'leads.bulk_status': 'Massen-Statusaktualisierung:',
    'leads.col_lead': 'Lead',
    'leads.col_company': 'Unternehmen',
    'leads.col_score': 'KI-Score',
    'leads.col_value': 'Geschätzter Wert',
    'leads.col_source': 'Quelle',
    'leads.col_status': 'Status',
    'leads.col_owner': 'Zuständig',
    'leads.col_actions': 'Aktionen',
    'leads.drawer_title': 'Lead-Profildetails',
    'leads.drawer_notes': 'Qualifizierungsnotizen & Erkenntnisse',
    'leads.delete_confirm_title': 'Lead-Datensatz löschen',
    'leads.delete_confirm_msg': 'Möchten Sie diesen Lead wirklich dauerhaft löschen? Diese Aktion kann nicht rückgängig gemacht werden.',

    // Contacts Page
    'contacts.title': 'Kundenkontakte',
    'contacts.subtitle': 'Direkte Ansprechpartner in Kundenunternehmen und Partnerorganisationen.',
    'contacts.new_contact': 'Kontakt hinzufügen',
    'contacts.search': 'Kontakte nach Name, Rolle, E-Mail suchen...',
    'contacts.col_name': 'Kontaktname',
    'contacts.col_account': 'Unternehmen / Kunde',
    'contacts.col_info': 'Kontaktdaten',
    'contacts.col_owner': 'Zuständig',
    'contacts.col_last_contact': 'Letzter Kontakt',
    'contacts.drawer_title': 'Kontakt-Profildetails',
    'contacts.delete_confirm_title': 'Kontakt löschen',
    'contacts.delete_confirm_msg': 'Möchten Sie diesen Ansprechpartner wirklich löschen?',

    // Companies Page
    'companies.title': 'Kundenkonten & Unternehmen',
    'companies.subtitle': 'Verzeichnis von Kundenunternehmen, Konzernen und Großkunden.',
    'companies.new_company': 'Unternehmen hinzufügen',
    'companies.search': 'Unternehmen nach Name, Branche, Stadt suchen...',
    'companies.col_name': 'Unternehmen / Kunde',
    'companies.col_vertical': 'Branche',
    'companies.col_rev': 'Jahresumsatz',
    'companies.col_size': 'Teamgröße',
    'companies.col_tier': 'Kunden-Tarif',
    'companies.col_location': 'Hauptsitz',
    'companies.drawer_title': 'Unternehmensprofil',
    'companies.delete_confirm_title': 'Unternehmenskonto löschen',
    'companies.delete_confirm_msg': 'Möchten Sie dieses Unternehmenskonto wirklich löschen?',

    // Deals Page
    'deals.title': 'Vertriebspipeline & Kanban',
    'deals.subtitle': 'Deal-Geschwindigkeit, Phasenfortschritt und Abschlusswahrscheinlichkeiten visualisieren.',
    'deals.new_deal': 'Deal hinzufügen',
    'deals.total_pipeline': 'Gesamte Pipeline',
    'deals.weighted_forecast': 'Gewichtete Prognose',
    'deals.avg_deal_size': 'Ø Deal-Größe',
    'deals.col_title': 'Deal-Titel',
    'deals.col_account': 'Unternehmen',
    'deals.col_stage': 'Phase',
    'deals.col_value': 'Deal-Wert',
    'deals.col_prob': 'Wahrscheinlichkeit',
    'deals.col_close': 'Geplantes Abschlussdatum',
    'deals.delete_confirm_title': 'Deal aus Pipeline löschen',
    'deals.delete_confirm_msg': 'Möchten Sie diesen Deal wirklich aus der Verkaufspipeline entfernen?',

    // Tasks Page
    'tasks.title': 'Aufgaben & Nachfassungen',
    'tasks.subtitle': 'Operative Aufgaben, Meilensteine, Anrufe und Vertriebs-To-Dos.',
    'tasks.new_task': 'Neue Aufgabe',
    'tasks.pending_tab': 'Ausstehende Aufgaben',
    'tasks.completed_tab': 'Erledigte Aufgaben',
    'tasks.col_task': 'Aufgabentitel',
    'tasks.col_related': 'Zugehöriges Unternehmen',
    'tasks.col_due': 'Fälligkeit',
    'tasks.col_priority': 'Priorität',
    'tasks.col_status': 'Status',
    'tasks.col_assignee': 'Zugewiesen an',
    'tasks.delete_confirm_title': 'Aufgabe löschen',
    'tasks.delete_confirm_msg': 'Möchten Sie diese Aufgabe wirklich löschen?',

    // Activities Page
    'activities.title': 'Aktivitäts-Stream & Audit-Protokoll',
    'activities.subtitle': 'Vollständige Chronologie von Anrufen, E-Mails, Demos, Meetings und Notizen.',
    'activities.log_activity': 'Aktivität erfassen',
    'activities.timeline_view': 'Aktivitäts-Zeitleiste',

    // Reports Page
    'reports.title': 'Umsatz- & Pipeline-Intelligence',
    'reports.subtitle': 'Management-Analysen, Konvertierungstrichter, Zielerreichung und Vertriebsleistung.',
    'reports.export_pdf': 'CSV exportieren',
    'reports.total_pipeline_val': 'Gesamter Pipeline-Wert',
    'reports.won_revenue_val': 'Gewonnener Umsatz',
    'reports.avg_deal_cycle': 'Durchschnittlicher Verkaufszyklus',
    'reports.win_conversion_rate': 'Abschlussquote',
    'reports.rep_leaderboard': 'Vertriebsmitarbeiter Quoten-Rangliste',
    'reports.col_rep': 'Mitarbeiter',
    'reports.col_deals_won': 'Gewonnene Deals',
    'reports.col_rev_lakhs': 'Umsatz (₹ Lakhs)',
    'reports.col_win_rate': 'Abschlussrate',
    'reports.col_quota': 'Zielerreichung',
    'reports.funnel_title': 'Konvertierungstrichter: Vom Lead zum Kunden',
    'reports.stage_breakdown': 'Pipeline-Verteilung nach Phasen',

    // AI Assistant
    'ai.title': 'Inbox KI-Assistent',
    'ai.subtitle': 'KI-gestützter Analyse-Copilot von Inbox Infotech für Vertriebsprognosen, Lead-Qualifizierung und Kunden-Nachfassaktionen.',
    'ai.gemini_badge': 'Gemini Bereit',
    'ai.clear_chat': 'Chatverlauf löschen',
    'ai.send': 'Senden',
    'ai.copilot_name': 'Inbox KI-Copilot',
    'ai.suggested_actions': 'Vorgeschlagene Aktionen',
    'ai.input_placeholder': 'Fragen Sie Inbox KI nach Umsatzprognosen, Lead-Zusammenfassungen oder E-Mail-Entwürfen...',
    'ai.prompt_deals_attention': 'Dringende Deals heute',
    'ai.prompt_top_leads': 'Höchste Lead-Prioritäten',
    'ai.prompt_draft_email': 'Folge-E-Mail entwerfen',
    'ai.prompt_closing_soon': 'Abschlüsse diesen Monat',

    // Admin Panel
    'admin.title': 'Admin & Governance Konsole',
    'admin.subtitle': 'Systemintegrität, Mitarbeiter-RBAC-Berechtigungen, Mandantenrichtlinien und Datensicherung.',
    'admin.super_access': 'Super Admin Zugriff',
    'admin.tab_users': 'Mitarbeiterzugriff & RBAC',
    'admin.tab_tenant': 'Mandanten-Arbeitsbereiche',
    'admin.tab_security': 'Sicherheits-Audit-Protokoll',
    'admin.tab_database': 'Datenbank-Sicherheitskopien',
    'admin.add_employee': 'Mitarbeiter anlegen',
    'admin.backup_db': 'Datenbank sichern (JSON)',
    'admin.factory_reset': 'CRM auf Werkseinstellungen',
    'admin.col_employee': 'Mitarbeitername',
    'admin.col_email': 'E-Mail-Adresse',
    'admin.col_role': 'Zugewiesene Rolle',
    'admin.col_dept': 'Abteilung',
    'admin.col_status': 'Kontostatus',
    'admin.col_actions': 'Aktionen',
    'admin.col_event': 'Aktion / Ereignis',
    'admin.col_user': 'Benutzerkonto',
    'admin.col_target': 'Ziel-Ressource',
    'admin.col_ip': 'IP-Adresse',
    'admin.col_timestamp': 'Zeitstempel',

    // Settings
    'settings.title': 'Systemadministration & Einstellungen',
    'settings.subtitle': 'Mandanten-Arbeitsbereiche, Autorisierungsrollen, Bewertungsregeln und Schnittstellen konfigurieren.',
    'settings.language_preference': 'Sprache & Region',
    'settings.select_language': 'Benutzeroberflächen-Sprache wählen',
    'settings.tab_org': 'Organisationsprofil',
    'settings.tab_team': 'Team & Rollen (RBAC)',
    'settings.tab_fields': 'Benutzerdefinierte Felder',
    'settings.tab_scoring': 'Lead-Bewertungsregeln',
    'settings.tab_api': 'API & Backend-Bereitschaft',
    'settings.org_info': 'Arbeitsbereich-Informationen',
    'settings.company_name': 'Firmen- / Arbeitsbereichsname',
    'settings.base_currency': 'Standard-Basiswährung',
    'settings.timezone': 'Zeitzone',
    'settings.fiscal_year': 'Beginn des Geschäftsjahres',
    'settings.save_profile': 'Profil speichern',

    // Login
    'login.title': 'Bei Inbox CRM anmelden',
    'login.admin_portal': 'Administrator-Portal',
    'login.employee_workspace': 'Mitarbeiter-Arbeitsbereich',
    'login.subtitle': 'Melden Sie sich an, um auf Ihre Inbox Infotech CRM-Instanz zuzugreifen',
    'login.work_email': 'Geschäftliche E-Mail',
    'login.password': 'Passwort',
    'login.remember_me': 'Dieses Gerät merken',
    'login.sign_in_btn': 'Am Arbeitsbereich anmelden',
    'login.quick_demo_roles': 'Demo-Rollen Schnellzugriff (1-Klick-Anmeldung)',
    'login.live_instance': 'Live Cloud-Instanz',
    'login.admin_tab': 'Admin',
    'login.staff_tab': 'Mitarbeiter',
    'login.email_required': 'Bitte geben Sie Ihre geschäftliche E-Mail-Adresse ein',
    'login.pass_required': 'Bitte geben Sie Ihr Passwort ein',
    'login.success': 'Anmeldung erfolgreich! Willkommen bei Inbox CRM.',
    'login.invalid': 'Ungültige E-Mail oder Passwort. Bitte überprüfen Sie Ihre Anmeldedaten.',
    'login.admin_login': 'Admin-Anmeldung',
    'login.staff_login': 'Mitarbeiter-Anmeldung',
    'login.forgot_password': 'Passwort vergessen?',
    'login.credentials_guide': 'Demo-Zugangsdaten Leitfaden',
    'login.autofill': 'Automatisch ausfüllen',
    'login.credentials_filled': 'Anmeldedaten ins Formular eingefügt!',
    'login.auth_failed': 'Authentifizierung fehlgeschlagen',
    'login.tls_encrypted': '256-Bit TLS-verschlüsselt',
    'login.preconfigured': 'Vorkonfiguriert',
    'login.log_in': 'Anmelden',
    'login.sign_in_as': 'Anmelden als {role}',
    'login.enter_password': 'Passwort eingeben',
    'login.rights_reserved': 'Alle Rechte vorbehalten • Enterprise CRM-Lösung',
    'login.signed_in_as': 'Erfolgreich angemeldet als {role}!',

    // Guide Modal
    'guide.title': 'NexusCRM Kunden-Demonstrations-Leitfaden',
    'guide.subtitle': 'Folgen Sie diesem 6-Schritte-Leitfaden, um Interessenten eine überzeugende SaaS-Demonstration vorzuführen.',
    'guide.tip': 'Demo-Tipp: Alle Daten in dieser Anwendung sind interaktiv und live im Speicher. Sie können Datensätze erstellen und Aktivitäten gefahrlos testen.',
    'guide.got_it': 'Verstanden, Demonstration starten',
  },
  nl: {
    // Nav items
    'nav.dashboard': 'Dashboard',
    'nav.leads': 'Leads',
    'nav.contacts': 'Contacten',
    'nav.companies': 'Bedrijven',
    'nav.deals': 'Deals & Pijplijn',
    'nav.tasks': 'Taken',
    'nav.activities': 'Activiteiten',
    'nav.reports': 'Rapporten & Analyses',
    'nav.ai': 'Inbox AI Assistent',
    'nav.admin': 'Beheerderspaneel',
    'nav.settings': 'Instellingen',
    'nav.rbac_role': 'RBAC-rol',
    'nav.tier_enterprise': 'Enterprise-abonnement',

    // TopNav
    'header.search_placeholder': 'Zoek leads, deals, contacten... (Druk op ↵)',
    'header.new_record': 'Nieuw record',
    'header.new_lead': 'Nieuwe lead',
    'header.new_deal': 'Nieuwe deal / kans',
    'header.new_task': 'Nieuwe taak',
    'header.log_activity': 'Activiteit vastleggen',
    'header.tenant': 'Werkruimte',
    'header.switch_tenant': 'Werkruimte wisselen',
    'header.select_tenant': 'Selecteer werkruimte',
    'header.simulate_role': 'Rol simuleren (RBAC)',
    'header.switch_role_title': 'Demo-gebruikersrol wisselen',
    'header.notifications': 'Meldingen',
    'header.mark_all_read': 'Alles als gelezen markeren',
    'header.admin_console': 'Beheerdersconsole',
    'header.workspace_settings': 'Werkruimte-instellingen',
    'header.sign_out': 'Uitloggen / Gebruiker wisselen',
    'header.toggle_theme': 'Kleurenthema wisselen',
    'header.language': 'Taal',
    'header.notif_lead_title': 'Nieuwe lead met hoge prioriteit (Score: 92/100)',
    'header.notif_lead_desc': 'Gaurav Bhasin van OmniRetail bezocht de prijscalculator.',
    'header.notif_deal_title': 'Deal-fase verplaatst naar Onderhandeling',
    'header.notif_deal_desc': 'ABC Technologies - CRM Implementatie verplaatst door Vikramaditya.',
    'header.notif_task_title': 'Taak vandaag vervallen',
    'header.notif_task_desc': 'Architectuurdemo inplannen met Rajesh Kulkarni.',
    'header.time_10m': '10 min. geleden',
    'header.time_1h': '1 uur geleden',
    'header.time_3h': '3 uur geleden',

    // Common Actions & Labels
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.create': 'Aanmaken',
    'common.filter': 'Filteren',
    'common.export': 'Exporteren',
    'common.export_csv': 'Exporteer CSV',
    'common.search': 'Zoeken',
    'common.actions': 'Acties',
    'common.view': 'Bekijken',
    'common.details': 'Details',
    'common.records': 'records',
    'common.close': 'Sluiten',
    'common.refresh': 'Vernieuwen',
    'common.previous': 'Vorige',
    'common.next': 'Volgende',
    'common.all': 'Alle',
    'common.status': 'Status',
    'common.priority': 'Prioriteit',
    'common.stage': 'Fase',
    'common.value': 'Waarde',
    'common.owner': 'Eigenaar',
    'common.assignee': 'Toegewezen aan',
    'common.date': 'Datum',
    'common.due_date': 'Vervaldatum',
    'common.loading': 'Laden...',
    'common.empty': 'Geen records gevonden',
    'common.confirm': 'Bevestigen',
    'common.copied': 'Gekopieerd naar klembord',
    'common.copy': 'Kopiëren',
    'common.processing': 'Verwerken...',
    'common.all_statuses': 'Alle statussen',
    'common.all_sources': 'Alle bronnen',
    'common.all_scores': 'Alle scores',
    'common.all_stages': 'Alle fases',
    'common.all_priorities': 'Alle prioriteiten',
    'common.all_types': 'Alle types',
    'common.all_verticals': 'Alle sectoren',
    'common.all_roles': 'Alle rollen',
    'common.kanban': 'Kanban',
    'common.list': 'Lijst',
    'common.overview': 'Overzicht',
    'common.name': 'Naam',
    'common.email': 'E-mail',
    'common.phone': 'Telefoon',
    'common.company': 'Bedrijf',
    'common.account': 'Account / Bedrijf',
    'common.role': 'Rol',
    'common.title': 'Titel',
    'common.description': 'Beschrijving',
    'common.type': 'Type',
    'common.source': 'Bron',
    'common.notes': 'Notities',
    'common.created': 'Aangemaakt',
    'common.updated': 'Bijgewerkt',
    'common.touchpoints': 'contactmomenten',
    'common.accounts': 'accounts',
    'common.scheduled': 'gepland',
    'common.opportunities': 'verkoopkansen',

    // Statuses
    'status.New': 'Nieuw',
    'status.Contacted': 'Gecontacteerd',
    'status.Qualified': 'Gekwalificeerd',
    'status.Unqualified': 'Niet gekwalificeerd',
    'status.Converted': 'Geconverteerd',
    'status.Proposal': 'Voorstel',
    'status.Negotiation': 'Onderhandeling',
    'status.Won': 'Gewonnen',
    'status.Lost': 'Verloren',
    'status.Completed': 'Voltooid',
    'status.Pending': 'In behandeling',
    'status.In Progress': 'In uitvoering',
    'status.Overdue': 'Achterstallig',
    'status.Active': 'Actief',
    'status.Inactive': 'Inactief',
    'status.Customer': 'Klant',
    'status.Prospect': 'Prospect',

    // Priorities
    'priority.Low': 'Laag',
    'priority.Medium': 'Gemiddeld',
    'priority.High': 'Hoog',
    'priority.Urgent': 'Urgent',

    // Roles
    'role.Super Admin': 'Super Admin',
    'role.Admin': 'Admin',
    'role.Manager': 'Manager',
    'role.Sales': 'Verkoop',
    'role.Viewer': 'Kijker',

    // Stages
    'stage.New': 'Ontdekking',
    'stage.Qualified': 'Gekwalificeerd',
    'stage.Proposal': 'Voorstel / RFP',
    'stage.Negotiation': 'Onderhandeling',
    'stage.Won': 'Gewonnen',
    'stage.Lost': 'Verloren',

    // Activity Types
    'activity.Call': 'Telefoongesprek',
    'activity.Email': 'E-mail',
    'activity.Meeting': 'Vergadering',
    'activity.Demo': 'Demo',
    'activity.Note': 'Notitie',
    'activity.Follow-up': 'Opvolging',

    // Sources
    'source.Website': 'Website',
    'source.Referral': 'Aanbeveling',
    'source.LinkedIn': 'LinkedIn',
    'source.Advertisement': 'Advertentie',
    'source.Cold Call': 'Koude acquisitie',

    // Periods
    'period.Today': 'Vandaag',
    'period.7 Days': '7 dagen',
    'period.30 Days': '30 dagen',
    'period.90 Days': '90 dagen',
    'period.This Year': 'Dit jaar',

    // Pagination
    'pagination.showing': 'Weergave',
    'pagination.to': 'tot',
    'pagination.of': 'van',
    'pagination.results': 'resultaten',
    'pagination.rows': 'Rijen:',
    'pagination.page': 'Pagina',

    // Modals
    'modal.create_lead_title': 'Nieuwe lead aanmaken',
    'modal.create_lead_subtitle': 'Voeg een prospect toe aan uw CRM-database met AI-scoring.',
    'modal.full_name': 'Volledige naam',
    'modal.company': 'Bedrijf / Organisatie',
    'modal.email': 'E-mail',
    'modal.phone': 'Telefoon',
    'modal.est_value': 'Geschatte waarde (₹)',
    'modal.acq_source': 'Wervingsbron',
    'modal.save_lead': 'Lead opslaan',
    'modal.create_deal_title': 'Nieuwe verkoopkans aanmaken',
    'modal.create_deal_subtitle': 'Voeg een deal rechtstreeks toe aan het Kanban-bord van de verkooppijplijn.',
    'modal.deal_title': 'Deal-titel',
    'modal.account_company': 'Klant / Bedrijf',
    'modal.deal_value': 'Dealwaarde (₹)',
    'modal.initial_stage': 'Beginfase',
    'modal.target_close_date': 'Verwachte sluitingsdatum',
    'modal.create_deal': 'Deal aanmaken',
    'modal.schedule_task_title': 'Nieuwe taak inplannen',
    'modal.schedule_task_subtitle': 'Wijs een actiepunt toe om het verkoopmomentum hoog te houden.',
    'modal.task_title': 'Taaktitel',
    'modal.related_account': 'Gerelateerd bedrijf',
    'modal.due_date': 'Vervaldatum',
    'modal.save_task': 'Taak opslaan',
    'modal.log_activity_title': 'Klantactiviteit vastleggen',
    'modal.log_activity_subtitle': 'Registreer contactmomenten via e-mail, telefoon of vergaderingen.',
    'modal.activity_type': 'Activiteitstype',
    'modal.subject': 'Onderwerp / Titel',
    'modal.discussion_notes': 'Gespreksnotities',
    'modal.record_activity': 'Activiteit vastleggen',
    'modal.convert_lead_title': 'Lead converteren naar contact & deal',
    'modal.convert_lead_desc': 'Converteer deze prospect naar een actieve verkoopkans en een zakelijk contactpersoon.',
    'modal.convert_create_deal': 'Maak een actieve kans aan in de verkooppijplijn',
    'modal.confirm_convert': 'Lead converteren',

    // Dashboard
    'dashboard.title': 'Executive CRM-dashboard',
    'dashboard.subtitle': 'Realtime pijplijnprestaties, conversietelemetrie en teamactiviteit.',
    'dashboard.live_badge': 'Live realtime',
    'dashboard.total_leads': 'Totaal aantal leads',
    'dashboard.new_inbound': 'Nieuwe inbound',
    'dashboard.open_deals': 'Openstaande deals',
    'dashboard.pipeline_value': 'Pijplijnwaarde',
    'dashboard.won_revenue': 'Gewonnen omzet',
    'dashboard.conversion_rate': 'Winstpercentage',
    'dashboard.revenue_chart_title': 'Omzetboekingen vs. quotumdoel (₹ Lakhs)',
    'dashboard.revenue_chart_subtitle': 'Maandelijkse gesloten omzet vergeleken met organisatiedoelen',
    'dashboard.closed_won_legend': 'Gewonnen (₹L)',
    'dashboard.quota_target_legend': 'Quotumdoel (₹L)',
    'dashboard.pipeline_overview': 'Verdeling van verkoopfases',
    'dashboard.active_forecast': 'Actieve gewogen winstvoorspelling',
    'dashboard.upcoming_tasks': 'Aankomende actietaken',
    'dashboard.high_intent_leads': 'Hoogwaardige AI-leads',
    'dashboard.recent_activities': 'Recente activiteiten',
    'dashboard.view_pipeline': 'Pijplijnbord bekijken',
    'dashboard.view_tasks': 'Bord bekijken',
    'dashboard.view_leads': 'Alle leads',
    'dashboard.view_activities': 'Auditlog',
    'dashboard.recent_touchpoints': 'Recente activiteiten',

    // Leads Page
    'leads.title': 'Leadbeheer',
    'leads.subtitle': 'Volg en kwalificeer verkoopprospects met geautomatiseerde AI-leadscoring.',
    'leads.new_lead_btn': 'Nieuwe lead',
    'leads.search_placeholder': 'Zoek leads op naam, e-mail, bedrijf...',
    'leads.score': 'AI-score',
    'leads.convert': 'Converteren',
    'leads.inspect': 'Profiel inspecteren',
    'leads.export': 'Exporteer CSV',
    'leads.filter_hot': 'AI-score > 80 (Heet)',
    'leads.filter_warm': 'AI-score > 60 (Warm)',
    'leads.bulk_selected': 'leads geselecteerd',
    'leads.bulk_status': 'Bulk status bijwerken:',
    'leads.col_lead': 'Lead',
    'leads.col_company': 'Bedrijf',
    'leads.col_score': 'AI-score',
    'leads.col_value': 'Geschatte waarde',
    'leads.col_source': 'Bron',
    'leads.col_status': 'Status',
    'leads.col_owner': 'Eigenaar',
    'leads.col_actions': 'Acties',
    'leads.drawer_title': 'Leadprofiel details',
    'leads.drawer_notes': 'Kwalificatienotities & inzichten',
    'leads.delete_confirm_title': 'Leadrecord verwijderen',
    'leads.delete_confirm_msg': 'Weet u zeker dat u deze lead definitief wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',

    // Contacts Page
    'contacts.title': 'Klantcontacten',
    'contacts.subtitle': 'Belangrijke contactpersonen, besluitvormers en communicatiekanalen.',
    'contacts.new_contact': 'Contact toevoegen',
    'contacts.search': 'Zoek contacten op naam, rol, e-mail...',
    'contacts.col_name': 'Contactpersoon',
    'contacts.col_account': 'Account / Bedrijf',
    'contacts.col_info': 'Contactgegevens',
    'contacts.col_owner': 'Eigenaar',
    'contacts.col_last_contact': 'Laatste contact',
    'contacts.drawer_title': 'Contactprofiel details',
    'contacts.delete_confirm_title': 'Contactpersoon verwijderen',
    'contacts.delete_confirm_msg': 'Weet u zeker dat u deze contactpersoon wilt verwijderen?',

    // Companies Page
    'companies.title': 'Bedrijfsaccounts & bedrijven',
    'companies.subtitle': 'Overzicht van klantorganisaties, corporaties en strategische accounts.',
    'companies.new_company': 'Bedrijf toevoegen',
    'companies.search': 'Zoek bedrijven op naam, sector, stad...',
    'companies.col_name': 'Bedrijf / Account',
    'companies.col_vertical': 'Industriesector',
    'companies.col_rev': 'Jaaromzet',
    'companies.col_size': 'Teamgrootte',
    'companies.col_tier': 'Klantniveau',
    'companies.col_location': 'Hoofdkantoor',
    'companies.drawer_title': 'Bedrijfsprofiel',
    'companies.delete_confirm_title': 'Bedrijfsaccount verwijderen',
    'companies.delete_confirm_msg': 'Weet u zeker dat u dit bedrijfsaccount wilt verwijderen?',

    // Deals Page
    'deals.title': 'Verkooppijplijn & Kanban',
    'deals.subtitle': 'Visualiseer dealsnelheid, fasevoortgang en omzetwaarschijnlijkheid.',
    'deals.new_deal': 'Deal toevoegen',
    'deals.total_pipeline': 'Totale pijplijn',
    'deals.weighted_forecast': 'Gewogen prognose',
    'deals.avg_deal_size': 'Gem. dealgrootte',
    'deals.col_title': 'Deal-titel',
    'deals.col_account': 'Account',
    'deals.col_stage': 'Fase',
    'deals.col_value': 'Dealwaarde',
    'deals.col_prob': 'Kans',
    'deals.col_close': 'Verwachte sluitingsdatum',
    'deals.delete_confirm_title': 'Deal uit pijplijn verwijderen',
    'deals.delete_confirm_msg': 'Weet u zeker dat u deze deal uit de verkooppijplijn wilt verwijderen?',

    // Tasks Page
    'tasks.title': 'Actiepunten & taken',
    'tasks.subtitle': 'Operationele taken, mijlpalen, telefoontjes en verkoopopvolgingen.',
    'tasks.new_task': 'Nieuwe taak',
    'tasks.pending_tab': 'Openstaande taken',
    'tasks.completed_tab': 'Voltooide taken',
    'tasks.col_task': 'Taaktitel',
    'tasks.col_related': 'Gerelateerd account',
    'tasks.col_due': 'Vervaldatum',
    'tasks.col_priority': 'Prioriteit',
    'tasks.col_status': 'Status',
    'tasks.col_assignee': 'Toegewezen aan',
    'tasks.delete_confirm_title': 'Taak verwijderen',
    'tasks.delete_confirm_msg': 'Weet u zeker dat u deze taak wilt verwijderen?',

    // Activities Page
    'activities.title': 'Activiteitenstroom & auditlog',
    'activities.subtitle': 'Volledige chronologie van gesprekken, e-mails, demo\'s en notities.',
    'activities.log_activity': 'Activiteit vastleggen',
    'activities.timeline_view': 'Activiteiten-tijdlijn',

    // Reports Page
    'reports.title': 'Omzet- & pijplijnintelligentie',
    'reports.subtitle': 'Executive analyses, conversietrechters, quotumbehalen en acquisitieprestaties.',
    'reports.export_pdf': 'Exporteer CSV',
    'reports.total_pipeline_val': 'Totale pijplijnwaarde',
    'reports.won_revenue_val': 'Gesloten gewonnen omzet',
    'reports.avg_deal_cycle': 'Gemiddelde verkoopcyclus',
    'reports.win_conversion_rate': 'Winstconversiepercentage',
    'reports.rep_leaderboard': 'Vertegenwoordigers quotum ranglijst',
    'reports.col_rep': 'Vertegenwoordiger',
    'reports.col_deals_won': 'Gewonnen deals',
    'reports.col_rev_lakhs': 'Omzet (₹ Lakhs)',
    'reports.col_win_rate': 'Winstpercentage',
    'reports.col_quota': 'Quotumbehalen',
    'reports.funnel_title': 'Conversietrechter: Van lead naar klant',
    'reports.stage_breakdown': 'Pijplijnverdeling per fase',

    // AI Assistant
    'ai.title': 'Inbox AI Assistent',
    'ai.subtitle': 'AI-gestuurde intelligentie-copilot van Inbox Infotech voor verkoopvoorspellingen, leadkwalificatie en klantopvolging.',
    'ai.gemini_badge': 'Gemini Gereed',
    'ai.clear_chat': 'Chatgeschiedenis wissen',
    'ai.send': 'Verzenden',
    'ai.copilot_name': 'Inbox AI Copilot',
    'ai.suggested_actions': 'Voorgestelde acties',
    'ai.input_placeholder': 'Vraag Inbox AI om omzet te voorspellen, leads samen te vatten of e-mails op te stellen...',
    'ai.prompt_deals_attention': 'Dringende deals vandaag',
    'ai.prompt_top_leads': 'Hoogste prioriteit leads',
    'ai.prompt_draft_email': 'Follow-up e-mail opstellen',
    'ai.prompt_closing_soon': 'Deals die deze maand sluiten',

    // Admin Panel
    'admin.title': 'Beheerders- & governancescherm',
    'admin.subtitle': 'Systeemstatus, RBAC-rechten van medewerkers, werkruimtebeleid en databasebescherming.',
    'admin.super_access': 'Super Admin Toegang',
    'admin.tab_users': 'Medewerkerstoegang & RBAC',
    'admin.tab_tenant': 'Werkruimten',
    'admin.tab_security': 'Beveiligingsauditlog',
    'admin.tab_database': 'Databasebeveiliging',
    'admin.add_employee': 'Medewerker toevoegen',
    'admin.backup_db': 'Database back-up (JSON)',
    'admin.factory_reset': 'CRM fabrieksinstellingen herstellen',
    'admin.col_employee': 'Medewerkersnaam',
    'admin.col_email': 'E-mailadres',
    'admin.col_role': 'Toegewezen rol',
    'admin.col_dept': 'Afdeling',
    'admin.col_status': 'Accountstatus',
    'admin.col_actions': 'Acties',
    'admin.col_event': 'Actie / Gebeurtenis',
    'admin.col_user': 'Gebruikersaccount',
    'admin.col_target': 'Doelbron',
    'admin.col_ip': 'IP-adres',
    'admin.col_timestamp': 'Tijdstempel',

    // Settings
    'settings.title': 'Systeembeheer & instellingen',
    'settings.subtitle': 'Configureer werkruimten, rollen, scoreregels en integraties.',
    'settings.language_preference': 'Taal & Regio',
    'settings.select_language': 'Interface-taal selecteren',
    'settings.tab_org': 'Organisatieprofiel',
    'settings.tab_team': 'Team & Rollen (RBAC)',
    'settings.tab_fields': 'Aangepaste velden',
    'settings.tab_scoring': 'Lead-scoreregels',
    'settings.tab_api': 'API & Backend gereedheid',
    'settings.org_info': 'Werkruimte-informatie',
    'settings.company_name': 'Bedrijfs- / Werkruimtenaam',
    'settings.base_currency': 'Standaard basisvaluta',
    'settings.timezone': 'Tijdzone',
    'settings.fiscal_year': 'Startmaand boekjaar',
    'settings.save_profile': 'Profiel opslaan',

    // Login
    'login.title': 'Inloggen bij Inbox CRM',
    'login.admin_portal': 'Beheerdersportaal',
    'login.employee_workspace': 'Medewerkerswerkruimte',
    'login.subtitle': 'Log in voor toegang tot uw Inbox Infotech CRM-instantie',
    'login.work_email': 'Zakelijk e-mailadres',
    'login.password': 'Wachtwoord',
    'login.remember_me': 'Dit apparaat onthouden',
    'login.sign_in_btn': 'Inloggen op werkruimte',
    'login.quick_demo_roles': 'Snelle demo-rollen (1-klik inloggen)',
    'login.live_instance': 'Live cloudinstantie',
    'login.admin_tab': 'Admin',
    'login.staff_tab': 'Medewerker',
    'login.email_required': 'Voer uw zakelijke e-mailadres in',
    'login.pass_required': 'Voer uw wachtwoord in',
    'login.success': 'Succesvol ingelogd! Welkom bij Inbox CRM.',
    'login.invalid': 'Ongeldig e-mailadres of wachtwoord. Controleer uw inloggegevens.',
    'login.admin_login': 'Admin inloggen',
    'login.staff_login': 'Medewerkers-inlog',
    'login.forgot_password': 'Wachtwoord vergeten?',
    'login.credentials_guide': 'Gids demo-inloggegevens',
    'login.autofill': 'Automatisch invullen',
    'login.credentials_filled': 'Inloggegevens ingevuld in formulier!',
    'login.auth_failed': 'Authenticatie mislukt',
    'login.tls_encrypted': '256-bits TLS versleuteld',
    'login.preconfigured': 'Vooraf geconfigureerd',
    'login.log_in': 'Inloggen',
    'login.sign_in_as': 'Inloggen als {role}',
    'login.enter_password': 'Voer wachtwoord in',
    'login.rights_reserved': 'Alle rechten voorbehouden • Enterprise CRM-oplossing',
    'login.signed_in_as': 'Succesvol ingelogd als {role}!',

    // Guide Modal
    'guide.title': 'NexusCRM Klantdemonstratiegids',
    'guide.subtitle': 'Volg dit 6-stappenplan om prospects een overtuigende SaaS-demonstratie te geven.',
    'guide.tip': 'Demotip: Alle gegevens in deze applicatie zijn live en interactief in het geheugen. U kunt veilig records aanmaken en acties uitproberen.',
    'guide.got_it': 'Begrepen, start demonstratie',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  currentLanguage: LanguageOption;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string, fallback?: string, params?: Record<string, string | number>) => string;
  tStatus: (status: string) => string;
  tPriority: (priority: string) => string;
  tRole: (role: string) => string;
  tStage: (stage: string) => string;
  tActivityType: (type: string) => string;
  tSource: (source: string) => string;
  tPeriod: (period: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'inbox_crm_language';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === 'de' || saved === 'en' || saved === 'nl') {
      return saved;
    }
    return 'en';
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    localStorage.setItem(STORAGE_KEY, code);
  };

  const currentLanguage = languages.find((l) => l.code === language) || languages[0];

  const t = (key: string, fallback?: string, params?: Record<string, string | number>): string => {
    let text = translations[language]?.[key] ?? translations.en?.[key] ?? fallback ?? key;
    if (params) {
      Object.entries(params).forEach(([paramKey, paramVal]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramVal));
      });
    }
    return text;
  };

  const tStatus = (status: string): string => {
    return translations[language]?.[`status.${status}`] ?? translations.en?.[`status.${status}`] ?? status;
  };

  const tPriority = (priority: string): string => {
    return translations[language]?.[`priority.${priority}`] ?? translations.en?.[`priority.${priority}`] ?? priority;
  };

  const tRole = (role: string): string => {
    return translations[language]?.[`role.${role}`] ?? translations.en?.[`role.${role}`] ?? role;
  };

  const tStage = (stage: string): string => {
    return translations[language]?.[`stage.${stage}`] ?? translations.en?.[`stage.${stage}`] ?? stage;
  };

  const tActivityType = (type: string): string => {
    return translations[language]?.[`activity.${type}`] ?? translations.en?.[`activity.${type}`] ?? type;
  };

  const tSource = (source: string): string => {
    return translations[language]?.[`source.${source}`] ?? translations.en?.[`source.${source}`] ?? source;
  };

  const tPeriod = (period: string): string => {
    return translations[language]?.[`period.${period}`] ?? translations.en?.[`period.${period}`] ?? period;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        currentLanguage,
        setLanguage,
        t,
        tStatus,
        tPriority,
        tRole,
        tStage,
        tActivityType,
        tSource,
        tPeriod,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
